# Variables for GPT-RAG Terraform deployment

variable "environment_name" {
  description = "Environment name used as a tag for all resources. This is directly mapped to the azd-environment."
  type        = string
  default     = ""
}

variable "location" {
  description = "Primary location for all resources."
  type        = string
}

variable "resource_group_name" {
  description = "Name of the resource group where all resources will be created. When empty, the name is autogenerated."
  type        = string
  default     = ""
}

variable "deployment_tags" {
  description = "Key-value pairs of tags to assign to all resources. The default azd tags are automatically added."
  type        = map(string)
  default     = {}
}

variable "principal_id" {
  description = "Id of the user or app to assign application roles"
  type        = string
  default     = ""
}

# Network Configuration
variable "network_isolation" {
  description = "Network isolation? If yes it will create the private endpoints."
  type        = bool
  default     = false
}

variable "deploy_vm" {
  description = "Deploy VM? If yes it will create the virtual machine to access the network isolated environment in the zero trust configuration."
  type        = bool
  default     = true
}

variable "vm_user_initial_password" {
  description = "Test vm gpt user password. Use strong password with letters and numbers. Needed only when choosing network isolation and create bastion option."
  type        = string
  sensitive   = true
}

variable "vm_user_name" {
  description = "Test vm gpt user name. Needed only when choosing network isolation and create bastion option."
  type        = string
  default     = "gptrag"
}

# VNet Settings
variable "vnet_name" {
  description = "Virtual network name, you can leave as it is to generate a random name."
  type        = string
  default     = ""
}

variable "vnet_address" {
  description = "Address space for the virtual network"
  type        = string
  default     = ""
}

variable "ai_subnet_name" {
  description = "Name of the AI services subnet"
  type        = string
  default     = ""
}

variable "ai_subnet_prefix" {
  description = "Address prefix for the AI services subnet"
  type        = string
  default     = ""
}

variable "bastion_subnet_prefix" {
  description = "Address prefix for the Bastion subnet"
  type        = string
  default     = ""
}

variable "app_int_subnet_name" {
  description = "Name of the App Integration subnet"
  type        = string
  default     = ""
}

variable "app_int_subnet_prefix" {
  description = "Address prefix for the App Integration subnet"
  type        = string
  default     = ""
}

variable "app_services_subnet_name" {
  description = "Name of the App Services subnet"
  type        = string
  default     = ""
}

variable "app_services_subnet_prefix" {
  description = "Address prefix for the App Services subnet"
  type        = string
  default     = ""
}

variable "database_subnet_name" {
  description = "Name of the Database subnet"
  type        = string
  default     = ""
}

variable "database_subnet_prefix" {
  description = "Address prefix for the Database subnet"
  type        = string
  default     = ""
}

# Database Configuration
variable "azure_db_config" {
  description = "Azure Database configuration"
  type = object({
    db_account_name                = string
    db_database_name               = string
    conversation_container_name    = string
    datasources_container_name     = string
  })
  default = {
    db_account_name                = ""
    db_database_name               = ""
    conversation_container_name    = "conversations"
    datasources_container_name     = "datasources"
  }
}

# Application Insights
variable "provision_application_insights" {
  description = "Provision Application Insights (and Log Analytics workspace) if true. Default is true."
  type        = bool
  default     = true
}

# Load Testing
variable "provision_load_testing" {
  description = "Disable load testing? If yes it will not create load testing resource."
  type        = bool
  default     = false
}

# Language Settings
variable "orchestrator_messages_language" {
  description = "Language used when orchestrator needs send error messages to the UX."
  type        = string
  default     = ""
}

variable "speech_recognition_language" {
  description = "Language used for speech recognition in the frontend."
  type        = string
  default     = ""
}

variable "speech_synthesis_language" {
  description = "Language used for speech synthesis in the frontend."
  type        = string
  default     = ""
}

variable "speech_synthesis_voice_name" {
  description = "Voice used for speech synthesis in the frontend."
  type        = string
  default     = ""
}

# Function App Settings
variable "func_app_runtime_version" {
  description = "Python runtime version in function apps"
  type        = string
  default     = ""
}

variable "app_service_runtime_version" {
  description = "Python runtime version in app service"
  type        = string
  default     = ""
}

# Azure OpenAI Settings
variable "chat_gpt_model_name" {
  description = "GPT model used to answer user questions. Don't forget to check region availability."
  type        = string
  default     = ""
}

variable "chat_gpt_model_deployment_type" {
  description = "GPT model deployment type."
  type        = string
  default     = "GlobalStandard"
}

variable "chat_gpt_model_version" {
  description = "GPT model version."
  type        = string
  default     = ""
}

variable "chat_gpt_deployment_name" {
  description = "GPT model deployment name."
  type        = string
  default     = ""
}

variable "chat_gpt_deployment_capacity" {
  description = "GPT model tokens per Minute Rate Limit (thousands)."
  type        = number
  default     = 0
}

variable "embeddings_model_name" {
  description = "Embeddings model used to generate vector embeddings. Don't forget to check region availability."
  type        = string
  default     = ""
}

variable "embeddings_deployment_type" {
  description = "Embeddings model deployment type."
  type        = string
  default     = "Standard"
}

variable "embeddings_model_version" {
  description = "Embeddings model version."
  type        = string
  default     = ""
}

variable "embeddings_deployment_name" {
  description = "Embeddings model deployment name."
  type        = string
  default     = ""
}

variable "embeddings_vector_size" {
  description = "Vector embeddings size."
  type        = number
  default     = 0
}

variable "embeddings_deployment_capacity" {
  description = "Embeddings model tokens per Minute Rate Limit (thousands)."
  type        = number
  default     = 0
}

variable "openai_api_version" {
  description = "Azure OpenAI API version."
  type        = string
  default     = ""
}

variable "chat_gpt_llm_monitoring" {
  description = "Enables LLM monitoring to generate conversation metrics."
  type        = bool
  default     = false
}

# AI Search Settings
variable "retrieval_approach" {
  description = "Orchestrator supports the following retrieval approaches: term, vector, hybrid(term + vector search), or use oyd feature of Azure OpenAI."
  type        = string
  default     = ""
}

variable "search_analyzer_name" {
  description = "Analyzer language used by Azure search to analyze indexes text content."
  type        = string
  default     = ""
}

variable "use_semantic_reranking" {
  description = "Use semantic reranking on top of search results?."
  type        = bool
  default     = false
}

variable "search_index" {
  description = "Search index name."
  type        = string
  default     = ""
}

variable "search_api_version" {
  description = "Search API version."
  type        = string
  default     = ""
}

variable "search_index_interval" {
  description = "Frequency of search reindexing. PT5M (5 min), PT1H (1 hour), P1D (1 day)."
  type        = string
  default     = ""
}

variable "search_use_mis" {
  description = "Use Search Service Managed Identity to Connect to data ingestion function?"
  type        = bool
  default     = false
}

# Chunking Settings
variable "chunk_num_tokens" {
  description = "The number of tokens in each chunk."
  type        = string
  default     = ""
}

variable "chunk_min_size" {
  description = "The minimum chunk size below which chunks will be filtered."
  type        = string
  default     = ""
}

variable "chunk_token_overlap" {
  description = "The number of tokens to overlap between chunks."
  type        = string
  default     = ""
}

# Storage Settings
variable "storage_container_name" {
  description = "Name of the container where source documents will be stored."
  type        = string
  default     = ""
}

variable "storage_account_name" {
  description = "Storage Account Name. Use your own name convention or leave as it is to generate a random name."
  type        = string
  default     = ""
}

# Resource Name Settings
variable "key_vault_name" {
  description = "Key Vault Name. Use your own name convention or leave as it is to generate a random name."
  type        = string
  default     = ""
}

variable "openai_service_name" {
  description = "OpenAI Service Name. Use your own name convention or leave as it is to generate a random name."
  type        = string
  default     = ""
}

variable "ai_services_name" {
  description = "AI services multi-service name. Use your own name convention or leave as it is to generate a random name."
  type        = string
  default     = ""
}

variable "app_service_plan_name" {
  description = "App Service Plan Name. Use your own name convention or leave as it is to generate a random name."
  type        = string
  default     = ""
}

variable "app_insights_name" {
  description = "App Insights Name. Use your own name convention or leave as it is to generate a random name."
  type        = string
  default     = ""
}

variable "app_service_name" {
  description = "Front-end App Service Name. Use your own name convention or leave as it is to generate a random name."
  type        = string
  default     = ""
}

variable "load_testing_name" {
  description = "Load testing resource name. Use your own name convention or leave as it is to generate a random name."
  type        = string
  default     = ""
}

variable "orchestrator_function_app_name" {
  description = "Orchestrator Function Name. Use your own name convention or leave as it is to generate a random name."
  type        = string
  default     = ""
}

variable "data_ingestion_function_app_name" {
  description = "Data Ingestion Function Name. Use your own name convention or leave as it is to generate a random name."
  type        = string
  default     = ""
}

variable "search_service_name" {
  description = "Search Service Name. Use your own name convention or leave as it is to generate a random name."
  type        = string
  default     = ""
}

# Private Endpoint Names
variable "azure_storage_account_pe" {
  description = "The name of the Azure Storage Account Private Endpoint. If left empty, a random name will be generated."
  type        = string
  default     = ""
}

variable "azure_db_account_pe" {
  description = "The name of the Azure Cosmos DB Private Endpoint. If left empty, a random name will be generated."
  type        = string
  default     = ""
}

variable "azure_keyvault_pe" {
  description = "The name of the Azure Key Vault Private Endpoint. If left empty, a random name will be generated."
  type        = string
  default     = ""
}

variable "azure_orchestrator_pe" {
  description = "The name of the Azure Orchestrator Private Endpoint. If left empty, a random name will be generated."
  type        = string
  default     = ""
}

variable "azure_frontend_pe" {
  description = "The name of the Azure Frontend Private Endpoint. If left empty, a random name will be generated."
  type        = string
  default     = ""
}

variable "azure_data_ingestion_pe" {
  description = "The name of the Azure Data Ingestion Private Endpoint. If left empty, a random name will be generated."
  type        = string
  default     = ""
}

variable "azure_ai_services_pe" {
  description = "The name of the Azure AI Services Private Endpoint. If left empty, a random name will be generated."
  type        = string
  default     = ""
}

variable "azure_openai_pe" {
  description = "The name of the Azure OpenAI Private Endpoint. If left empty, a random name will be generated."
  type        = string
  default     = ""
}

variable "azure_search_pe" {
  description = "The name of the Azure Search Private Endpoint. If left empty, a random name will be generated."
  type        = string
  default     = ""
}

# VM Settings
variable "vm_kv_secret_name" {
  description = "The name of the VM Key Vault Secret. If left empty, a random name will be generated."
  type        = string
  default     = ""
}

variable "zt_vm_name" {
  description = "The name of the Zero Trust VM. If left empty, a random name will be generated."
  type        = string
  default     = ""
}

variable "bastion_kv_name" {
  description = "The name of the Bastion Key Vault. If left empty, a random name will be generated."
  type        = string
  default     = ""
}

# Azure Reuse Configuration - for reusing existing resources
variable "azure_reuse_config" {
  description = "Settings to define reusable resources."
  type = object({
    aoai_reuse                                                 = bool
    existing_aoai_resource_group_name                         = string
    existing_aoai_name                                        = string
    app_insights_reuse                                        = bool
    existing_app_insights_resource_group_name                 = string
    existing_app_insights_name                                = string
    log_analytics_workspace_reuse                             = bool
    existing_log_analytics_workspace_resource_id              = string
    app_service_plan_reuse                                    = bool
    existing_app_service_plan_resource_group_name             = string
    existing_app_service_plan_name                            = string
    ai_search_reuse                                           = bool
    existing_ai_search_resource_group_name                    = string
    existing_ai_search_name                                   = string
    ai_services_reuse                                         = bool
    existing_ai_services_resource_group_name                  = string
    existing_ai_services_name                                 = string
    cosmos_db_reuse                                           = bool
    existing_cosmos_db_resource_group_name                    = string
    existing_cosmos_db_account_name                           = string
    existing_cosmos_db_database_name                          = string
    key_vault_reuse                                           = bool
    existing_key_vault_resource_group_name                    = string
    existing_key_vault_name                                   = string
    storage_reuse                                             = bool
    existing_storage_resource_group_name                      = string
    existing_storage_name                                     = string
    vnet_reuse                                                = bool
    existing_vnet_resource_group_name                         = string
    existing_vnet_name                                        = string
    orchestrator_function_app_reuse                           = bool
    existing_orchestrator_function_app_resource_group_name    = string
    existing_orchestrator_function_app_name                   = string
    data_ingestion_function_app_reuse                         = bool
    existing_data_ingestion_function_app_resource_group_name  = string
    existing_data_ingestion_function_app_name                 = string
    app_service_reuse                                         = bool
    existing_app_service_name                                 = string
    existing_app_service_name_resource_group_name             = string
    orchestrator_function_app_storage_reuse                   = bool
    existing_orchestrator_function_app_storage_name           = string
    existing_orchestrator_function_app_storage_resource_group_name = string
    data_ingestion_function_app_storage_reuse                 = bool
    existing_data_ingestion_function_app_storage_name         = string
    existing_data_ingestion_function_app_storage_resource_group_name = string
  })
  default = {
    aoai_reuse                                                 = false
    existing_aoai_resource_group_name                         = ""
    existing_aoai_name                                        = ""
    app_insights_reuse                                        = false
    existing_app_insights_resource_group_name                 = ""
    existing_app_insights_name                                = ""
    log_analytics_workspace_reuse                             = false
    existing_log_analytics_workspace_resource_id              = ""
    app_service_plan_reuse                                    = false
    existing_app_service_plan_resource_group_name             = ""
    existing_app_service_plan_name                            = ""
    ai_search_reuse                                           = false
    existing_ai_search_resource_group_name                    = ""
    existing_ai_search_name                                   = ""
    ai_services_reuse                                         = false
    existing_ai_services_resource_group_name                  = ""
    existing_ai_services_name                                 = ""
    cosmos_db_reuse                                           = false
    existing_cosmos_db_resource_group_name                    = ""
    existing_cosmos_db_account_name                           = ""
    existing_cosmos_db_database_name                          = ""
    key_vault_reuse                                           = false
    existing_key_vault_resource_group_name                    = ""
    existing_key_vault_name                                   = ""
    storage_reuse                                             = false
    existing_storage_resource_group_name                      = ""
    existing_storage_name                                     = ""
    vnet_reuse                                                = false
    existing_vnet_resource_group_name                         = ""
    existing_vnet_name                                        = ""
    orchestrator_function_app_reuse                           = false
    existing_orchestrator_function_app_resource_group_name    = ""
    existing_orchestrator_function_app_name                   = ""
    data_ingestion_function_app_reuse                         = false
    existing_data_ingestion_function_app_resource_group_name  = ""
    existing_data_ingestion_function_app_name                 = ""
    app_service_reuse                                         = false
    existing_app_service_name                                 = ""
    existing_app_service_name_resource_group_name             = ""
    orchestrator_function_app_storage_reuse                   = false
    existing_orchestrator_function_app_storage_name           = ""
    existing_orchestrator_function_app_storage_resource_group_name = ""
    data_ingestion_function_app_storage_reuse                 = false
    existing_data_ingestion_function_app_storage_name         = ""
    existing_data_ingestion_function_app_storage_resource_group_name = ""
  }
}
